// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import StarsController from "./stars_controller"
import MovieSearchController from "./movie_search_controller"

application.register("stars", StarsController)
application.register("movie-search", MovieSearchController)
